// Code generated by cmd/reset. DO NOT EDIT.

package model

// Reset сбрасывает все поля ResetableStruct к начальным значениям
func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.I = 0
	r.Str = ""
	if r.StrP != nil {
		*r.StrP = ""
	}
	r.S = r.S[:0]
	clear(r.M)
	if r.Child != nil {
		if resetter, ok := interface{}(r.Child).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*r.Child = ResetableStruct{}
		}
	}
}

// Reset сбрасывает все поля SimpleStruct к начальным значениям
func (s *SimpleStruct) Reset() {
	if s == nil {
		return
	}

	s.ID = 0
	s.Name = ""
	s.Active = false
	s.Score = 0
	s.Counter = 0
}
